version: 3.0.0

pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: 'wespeaker_voxceleb_resnet34_LM.onnx'
    embedding_batch_size: 1
    embedding_exclude_overlap: true
    segmentation: 'pyannote_vad_v3.bin'
    segmentation_batch_size: 32

params:
  clustering:
    method: centroid
    min_cluster_size: 12
    threshold: 0.7045654963945799
  segmentation:
    min_duration_off: 0.0
